# Generated by Django 3.2.8 on 2021-10-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0002_minuman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minuman',
            old_name='dingin',
            new_name='harga',
        ),
        migrations.RenameField(
            model_name='minuman',
            old_name='panas',
            new_name='nama',
        ),
    ]
